const names = {
    male: [
        //A
            //{name: "Aldrin", meaning: "El viejo", origin: "Nórdico"},
            {name: "Aldor", meaning: "Guerrero noble", origin: "Antiguo idioma de los guardianes del bosque"},
            {name: "Alerion", meaning: "Espíritu de las montañas", origin: "Lengua de los ancestros de las cumbres"},
            {name: "Arvion", meaning: "Guerrero de las estrellas", origin: "Dialecto de los celestiales"},
            {name: "Antrion", meaning: "Guardián de la sombra", origin: "Lenguaje de los vigilantes nocturnos"},
            {name: "Aendor", meaning: "Voz del trueno", origin: "Idioma de los pueblos de las tormentas"},
            {name: "Aelric", meaning: "Noble en batalla", origin: "Lengua d elos caballeros antiguos"},
            {name: "Athran", meaning: "Hijo del viento", origin: "Dialecto de los nómadas del aire"},
            {name: "Aranthor", meaning: "Señor de la luz", origin: "Idioma de los protectores del amanecer"},
            {name: "Averos", meaning: "El Valiente", origin: "Lengua d elos guerreros errantes"},
            {name: "Asgalor", meaning: "Fuego del corazón", origin: "Idioma de los hechiceros de la llama"},
            {name: "Aithor", meaning: "Heraldo del destino", origin: "Lenguaje de los Oráculos Antiguos"},
        //B
            //{name: "Bran", meaning: "Cuervo", origin: "Celta"},
            //{name: "Baldric", meaning: "Gobernante audaz", origin: "Germánico"},
            {name: "Branok", meaning: "Fuerte como el acero", origin: "Lengua de los forjadores de montañas"},
            {name: "Balarion", meaning: "Rey de la guerra", origin: "Dialecto de los conquistadores"},
            {name: "Byronn", meaning: "Héroe de la tierra", origin: "Idioma de los guardianes de los bosques"},
            {name: "Baelor", meaning: "El invencible", origin: "Lengua de los guerreros legendarios"},
            {name: "Braknar", meaning: "Destructor de fortalezas", origin: "Idioma de los invasores de las montañas"},
            {name: "Briathor", meaning: "Maestro del viento", origin: "Lenguaje de los magos del aire"},
            {name: "Barion", meaning: "El valiente navegante", origin: "Dialecto de los piratas de los mares lejanos"},
            {name: "Brendor", meaning: "Espíritu de batalla", origin: "Lengua de los clanes bárbaros"},
            {name: "Bodrik", meaning: "Defensor del reino", origin: "Idioma de los guardianes imperiales"},
            {name: "Brenmir", meaning: "Significado: Hijo de la tormenta", origin: "Dialecto de los viajeros del trueno"},
            {name: "Brodinor", meaning: "Señor de la resistencia", origin: "Lengua de los defensores del mundo subterráneo"},
        //C
            //{name: "Cedric", meaning: "Líder de la guerra", origin: "Inglés"},
            {name: "Caelum", meaning: "Cielo estrellado", origin: "Idioma de los sabios celestiales"},
            {name: "Caldrin", meaning: "Espíritu de hielo", origin: "Idioma de los guerreros de las tierras heladas"},
            {name: "Caspion", meaning: "Brillo de las estrellas", origin: "Lengua de los guardianes de los cielos"},
            {name: "Cravon", meaning: "Martillo de los dioses", origin: "Dialecto de los herreros divinos"},
            {name: "Caerdor", meaning: "Señor del fuego", origin: "Lengua de los druidas volcánicos"},
            {name: "Cendrik", meaning: "Guardián de las llanuras", origin: "Idioma de los protectores de las tierras abiertas"},
            {name: "Cazmir", meaning: "Hijo del cosmos", origin: "Dialecto de los navegantes estelares"},
            {name: "Corlith", meaning: "Espada de la justicia", origin: "Lenguaje de los campeones de la ley"},
            {name: "Cyrodor", meaning: "Significado: Espíritu indomable", origin: "Lengua de los aventureros sin miedo"},
            {name: "Calthor", meaning: "Destructor de sombras", origin: "Dialecto de los cazadores nocturnos"},
            {name: "Cromar", meaning: "Forjador de reinos", origin: "Lenguaje de los constructores de imperios"},
        //D
            //{name: "Dorian", meaning: "Descendiente de Doros", origin: "Griego"},
            {name: "Draven", meaning: "Potector de la oscuridad", origin: "Dialecto de los guardianes nocturnos"},
            {name: "Dargoth", meaning: "Bestia de las profundidades", origin: "Dialecto de los seres subterráneos"},
            {name: "Draegon", meaning: "Hijo del dragón", origin: "Lengua de los descendientes de dragones"},
            {name: "Durion", meaning: "Fuerte como la roca", origin: "Idioma de los guardianes de piedra"},
            {name: "Dareon", meaning: "El que desafía a los dioses", origin: "Lenguaje de los héroes rebeldes"},
            {name: "Darnak", meaning: "Martillo del destino", origin: "Dialecto de los herreros de las estrellas"},
            {name: "Dorianth", meaning: "Guardián de los cielos", origin: "Lengua de los celestiales alados"},
            {name: "Drithor", meaning: "Viento del desierto", origin: "Idioma de los nómadas de las dunas"},
            {name: "Dromar", meaning: "Señor del hierro", origin: "Lengua de los maestros forjadores"},
            {name: "Delron", meaning: "Líder de los sabios", origin: "Dialecto de los eruditos de la torre eterna"},
            {name: "Dagriel", meaning: "Mensajero de la luna", origin: "Lenguaje de los guardianes nocturnos"},
        //E
            //{name: "Elric", meaning: "gobernante eterno", origin: "Germánico"},
            {name: "Eldric", meaning: "Rey sabio", origin: "Lenguajede la antigua dinastía"},
            {name: "Erian", meaning: "Hijo del sol", origin: "Dialecto de los habitantes del desierto"},
            {name: "Elvor", meaning: "Guardián del bosque", origin: "Lengua de los druidas verdes"},
            {name: "Endrel", meaning: "Cazador de sombras", origin: "Idioma de los protectores nocturnos"},
            {name: "Eldrinor", meaning: "Sabio de la magia antigua", origin: "Dialecto de los archimagos"},
            {name: "Erendir", meaning: "Señor de los vientos", origin: "Lenguaje de los caballeros voladores"},
            {name: "Eosthor", meaning: "Protector de la llama", origin: "Lengua de los sacerdotes del fuego sagrado"},
            {name: "Edricon", meaning: "El elegido de los dioses", origin: "Dialecto de los oráculos místicos"},
            {name: "Enarik ", meaning: "Voz del trueno", origin: "Idioma de los vikingos del cielo"},
            {name: "Eldamar", meaning: "Rey de los mares", origin: "Lengua de los antiguos navegantes"},
            {name: "Ethlor", meaning: "Portador de la sabiduría", origin: "Lenguaje de los sabios ancestrales"},
        //F
            {name: "Fenric", meaning: "Lobo feroz / Vengador", origin: "Lengua de los defensores ancestrales - Nórdico"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        //G
            {name: "Galdor", meaning: "Canto de magia", origin: "Idioma de los bardos encantadores"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        //H
            {name: "Haldric", meaning: "Líder de la fortaleza", origin: "Lengua de los defensores ancestrales"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        //I
            {name: "Ivoran", meaning: "Guardián de los secretos", origin: "Dialecto de los custodios de conocimiento"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        //J
            {name: "Jareth", meaning: "Guerrero de fuego", origin: "Lenguaje de los descendientes de la lava"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        //K
            {name: "Kaelthor", meaning: "Destructor de sombras", origin: "Lengua de los luchadores de luz"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        //L
            {name: "Lorian", meaning: "Luz de la esperanza", origin: "Idioma de los iluminadores del amanecer"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        //M
            {name: "Maldrek", meaning: "Destructor de enemigos", origin: "Dialecto de los guerreros del caos"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        //N
            {name: "Nerion", meaning: "Hijo del océano", origin: "Lenguaje de los navegantes del mar"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        //Ñ
        //O
            {name: "Orinols", meaning: "Estrella fugaz", origin: "Idioma de los astrónomos místicos"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        //P
            {name: "Pyron", meaning: "Fuego eterno", origin: "Lengua de los maestros del volcán"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        //Q
            {name: "Quorim", meaning: "Guardián de la verdad", origin: "Dialecto de los consejeros sangrados"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        //R
            {name: "Ragnar", meaning: "Guerrero del trueno", origin: "Lengua de los vikingos míticos"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        //S
            {name: "Sylas", meaning: "Protector de los bosques", origin: "Idioma de los druida ancestrales"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        //T
            {name: "Thalon", meaning: "Noble y fuerte", origin: "Lenguaje de los señores del reino"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        //U
            {name: "Ulyric", meaning: "Legado de sabiduría", origin: "Dialecto de los eruditos de la Antigua Orden"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        //V
            {name: "Varek", meaning: "Destructor de la oscuridad", origin: "Lengua de los Campeones de la Luz"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        //W
            {name: "Wraithor", meaning: "Espíritu guardián", origin: "Idioma de los seres etéreos"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        //X
            {name: "Xandar", meaning: "Defensor de la paz", origin: "Lenuaje de los pacificadores de la era dorada"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        //Y
            {name: "Yorin", meaning: "Amigo leal", origin: "Dialecto de los clanes de los bosques"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        //Z
            {name: "Zarek", meaning: "Sombra del dragón", origin: "Lengua de los descendientes de los dragones"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        {name: "", meaning: "", origin: ""},
/*Me puedes generar una lista de nombres masculinos con todas las letras del abecedario, que tengan significado, un origen y que estos nombres sean de fantasia?*/
        // Agrega más nombres aquí
    ],
    female: [
        { name: "Aeliana", meaning: "Del Sol", origin: "Latino" },
        { name: "Briala", meaning: "Puede ser una variante de Briana", origin: "Desconocido" },
        { name: "Calia", meaning: "Bella", origin: "Griego" },
        { name: "Eldira", meaning: "Usado en literatura de fantasía", origin: "Ficticio" },
        { name: "Fiona", meaning: "Blanca", origin: "Gaélico" },
        { name: "Beatrix", meaning: "Viajera", origin: "Latino" },
        { name: "Callista", meaning: "La más hermosa", origin: "Griego" },
        // Agrega más nombres aquí
    ],
    nonBinary: [
        { name: "Arin", meaning: "Luz", origin: "Hebreo" },
        { name: "Bryn", meaning: "Colina", origin: "Galés" },
        { name: "Dru", meaning: "Sabio", origin: "Celta" },
        { name: "Ezra", meaning: "Ayuda", origin: "Hebreo" },
        { name: "Kai", meaning: "Mar", origin: "Hawaiano" },
        { name: "Briar", meaning: "Zarza", origin: "Inglés" },
        { name: "Ciel", meaning: "Cielo", origin: "Francés" },
        // Agrega más nombres aquí
    ]
};


function generateName() {
    const gender = document.getElementById('gender').value;
    const initial = document.getElementById('initial').value;
    const nameList = names[gender];

    if (!nameList || nameList.length === 0) {
        alert("No hay nombres disponibles para este género.");
        return;
    }

    // Filtrar los nombres por la inicial seleccionada
    const filteredNames = initial ? nameList.filter(name => name.name.startsWith(initial)) : nameList;
    
    // Verificar si la lista filtrada está vacía
    if (filteredNames.length === 0) {
        alert(`No hay nombres disponibles que empiecen con la letra "${initial}".`);
        return;  // Detener la ejecución si no hay nombres disponibles
    }

    const randomIndex = Math.floor(Math.random() * filteredNames.length);
    const randomName = filteredNames[randomIndex];
    
// Crear el mensaje con el nombre, significado y origen usando etiquetas HTML con clases
    const message = 
                    `<span class="name-title">Nombre:</span> <span class="name">${randomName.name}<br>` +
                    `<span class="meaning-title">Significado:</span> <span class="meaning">${randomName.meaning}<br>` +
                    `<span class="origin-title">Origen:</span> <span class="origin">${randomName.origin}</span>`;
    
    // Mostrar el mensaje en una ventana emergente
    //alert(message);
    
    // También puedes mostrar el nombre en el área designada si lo prefieres
    document.getElementById('name-output').innerHTML = message;
    // Usamos .innerHTML en lugar de .textContent para insertar HTML (como <br>) en el contenido del elemento.
}
// Puedo agregarle también la raza del personaje, origen, inicial, etc.
