const names = {
    male: [
        //A {name: "", meaning: "", origin: ""},
            //{name: "Aldrin", meaning: "El viejo", origin: "Nórdico"},
            {name: "Aldor", meaning: "Guerrero noble", origin: "Antiguo idioma de los guardianes del bosque"},
            {name: "Alerion", meaning: "Espíritu de las montañas", origin: "Lengua de los ancestros de las cumbres"},
            {name: "Arvion", meaning: "Guerrero de las estrellas", origin: "Dialecto de los celestiales"},
            {name: "Antrion", meaning: "Guardián de la sombra", origin: "Lenguaje de los vigilantes nocturnos"},
            {name: "Aendor", meaning: "Voz del trueno", origin: "Idioma de los pueblos de las tormentas"},
            {name: "Aelric", meaning: "Noble en batalla", origin: "Lengua d elos caballeros antiguos"},
            {name: "Athran", meaning: "Hijo del viento", origin: "Dialecto de los nómadas del aire"},
            {name: "Aranthor", meaning: "Señor de la luz", origin: "Idioma de los protectores del amanecer"},
            {name: "Averos", meaning: "El Valiente", origin: "Lengua d elos guerreros errantes"},
            {name: "Asgalor", meaning: "Fuego del corazón", origin: "Idioma de los hechiceros de la llama"},
            {name: "Aithor", meaning: "Heraldo del destino", origin: "Lenguaje de los Oráculos Antiguos"},
        //B
            //{name: "Bran", meaning: "Cuervo", origin: "Celta"},
            //{name: "Baldric", meaning: "Gobernante audaz", origin: "Germánico"},
            {name: "Branok", meaning: "Fuerte como el acero", origin: "Lengua de los forjadores de montañas"},
            {name: "Balarion", meaning: "Rey de la guerra", origin: "Dialecto de los conquistadores"},
            {name: "Byronn", meaning: "Héroe de la tierra", origin: "Idioma de los guardianes de los bosques"},
            {name: "Baelor", meaning: "El invencible", origin: "Lengua de los guerreros legendarios"},
            {name: "Braknar", meaning: "Destructor de fortalezas", origin: "Idioma de los invasores de las montañas"},
            {name: "Briathor", meaning: "Maestro del viento", origin: "Lenguaje de los magos del aire"},
            {name: "Barion", meaning: "El valiente navegante", origin: "Dialecto de los piratas de los mares lejanos"},
            {name: "Brendor", meaning: "Espíritu de batalla", origin: "Lengua de los clanes bárbaros"},
            {name: "Bodrik", meaning: "Defensor del reino", origin: "Idioma de los guardianes imperiales"},
            {name: "Brenmir", meaning: "Significado: Hijo de la tormenta", origin: "Dialecto de los viajeros del trueno"},
            {name: "Brodinor", meaning: "Señor de la resistencia", origin: "Lengua de los defensores del mundo subterráneo"},
        //C
            //{name: "Cedric", meaning: "Líder de la guerra", origin: "Inglés"},
            {name: "Caelum", meaning: "Cielo estrellado", origin: "Idioma de los sabios celestiales"},
            {name: "Caldrin", meaning: "Espíritu de hielo", origin: "Idioma de los guerreros de las tierras heladas"},
            {name: "Caspion", meaning: "Brillo de las estrellas", origin: "Lengua de los guardianes de los cielos"},
            {name: "Cravon", meaning: "Martillo de los dioses", origin: "Dialecto de los herreros divinos"},
            {name: "Caerdor", meaning: "Señor del fuego", origin: "Lengua de los druidas volcánicos"},
            {name: "Cendrik", meaning: "Guardián de las llanuras", origin: "Idioma de los protectores de las tierras abiertas"},
            {name: "Cazmir", meaning: "Hijo del cosmos", origin: "Dialecto de los navegantes estelares"},
            {name: "Corlith", meaning: "Espada de la justicia", origin: "Lenguaje de los campeones de la ley"},
            {name: "Cyrodor", meaning: "Significado: Espíritu indomable", origin: "Lengua de los aventureros sin miedo"},
            {name: "Calthor", meaning: "Destructor de sombras", origin: "Dialecto de los cazadores nocturnos"},
            {name: "Cromar", meaning: "Forjador de reinos", origin: "Lenguaje de los constructores de imperios"},
        //D
            //{name: "Dorian", meaning: "Descendiente de Doros", origin: "Griego"},
            {name: "Draven", meaning: "Potector de la oscuridad", origin: "Dialecto de los guardianes nocturnos"},
            {name: "Dargoth", meaning: "Bestia de las profundidades", origin: "Dialecto de los seres subterráneos"},
            {name: "Draegon", meaning: "Hijo del dragón", origin: "Lengua de los descendientes de dragones"},
            {name: "Durion", meaning: "Fuerte como la roca", origin: "Idioma de los guardianes de piedra"},
            {name: "Dareon", meaning: "El que desafía a los dioses", origin: "Lenguaje de los héroes rebeldes"},
            {name: "Darnak", meaning: "Martillo del destino", origin: "Dialecto de los herreros de las estrellas"},
            {name: "Dorianth", meaning: "Guardián de los cielos", origin: "Lengua de los celestiales alados"},
            {name: "Drithor", meaning: "Viento del desierto", origin: "Idioma de los nómadas de las dunas"},
            {name: "Dromar", meaning: "Señor del hierro", origin: "Lengua de los maestros forjadores"},
            {name: "Delron", meaning: "Líder de los sabios", origin: "Dialecto de los eruditos de la torre eterna"},
            {name: "Dagriel", meaning: "Mensajero de la luna", origin: "Lenguaje de los guardianes nocturnos"},
        //E
            //{name: "Elric", meaning: "gobernante eterno", origin: "Germánico"},
            {name: "Eldric", meaning: "Rey sabio", origin: "Lenguajede la antigua dinastía"},
            {name: "Erian", meaning: "Hijo del sol", origin: "Dialecto de los habitantes del desierto"},
            {name: "Elvor", meaning: "Guardián del bosque", origin: "Lengua de los druidas verdes"},
            {name: "Endrel", meaning: "Cazador de sombras", origin: "Idioma de los protectores nocturnos"},
            {name: "Eldrinor", meaning: "Sabio de la magia antigua", origin: "Dialecto de los archimagos"},
            {name: "Erendir", meaning: "Señor de los vientos", origin: "Lenguaje de los caballeros voladores"},
            {name: "Eosthor", meaning: "Protector de la llama", origin: "Lengua de los sacerdotes del fuego sagrado"},
            {name: "Edricon", meaning: "El elegido de los dioses", origin: "Dialecto de los oráculos místicos"},
            {name: "Enarik ", meaning: "Voz del trueno", origin: "Idioma de los vikingos del cielo"},
            {name: "Eldamar", meaning: "Rey de los mares", origin: "Lengua de los antiguos navegantes"},
            {name: "Ethlor", meaning: "Portador de la sabiduría", origin: "Lenguaje de los sabios ancestrales"},
        //F
            {name: "Fenric", meaning: "Lobo feroz / Vengador", origin: "Lengua de los defensores ancestrales - Nórdico"},
            {name: "Faldorn", meaning: "Guardián del bosque antiguo", origin: "Lengua de los druidas ancestrales"},
            {name: "Feyron", meaning: "Portador de luz", origin: "Dialecto de los iluminadores celestiales"},
            {name: "Furion", meaning: "Viento de la batalla", origin: "Idioma de los nómadas guerreros"},
            {name: "Faeron", meaning: "Hijo de la esperanza", origin: "Lengua de los habitantes del amanecer"},
            {name: "Forlorn", meaning: "El errante solitario", origin: "Idioma de los caminantes de las tierras desoladas"},
            {name: "Fendric", meaning: "Defensor del reino", origin: "Dialecto de los caballeros de la frontera"},
            {name: "Fenthil", meaning: "Guardián de los secretos", origin: "Lengua de los espías del consejo"},
            {name: "Frondar", meaning: "Fuerza de los árboles", origin: " Idioma de los ancestros del bosque viviente"},
            {name: "Ferion", meaning: "Espíritu del fuego", origin: "Dialecto de los hechiceros volcánicos"},
            {name: "Faldrik", meaning: "Protector de la verdad", origin: "Lengua de los guardianes del conocimiento"},
        //G
            {name: "Galdor", meaning: "Canto de magia", origin: "Idioma de los bardos encantadores"},
            {name: "Garrion", meaning: "Guerrero indomable", origin: "Dialecto de los luchadores salvajes"},
            {name: "Galdric", meaning: "Sabio de las estrellas", origin: "Lengua de los astrólogos del reino eterno"},
            {name: "Grymthor", meaning: "Señor de los vientos", origin: "Idioma de los navegantes aéreos"},
            {name: "Galvon", meaning: "Martillo del trueno", origin: " Lengua de los forjadores de tormentas"},
            {name: "Gorathor", meaning: "Hijo de las montañas", origin: "Dialecto de los gigantes de piedra"},
            {name: "Gavriel", meaning: "El mensajero celestial", origin: "Idioma de los heraldos divinos"},
            {name: "Gleonor", meaning: " Luchador del alba", origin: "Lengua de los caballeros del amanecer"},
            {name: "Gorion", meaning: "El guardián oscuro", origin: "Dialecto de los vigilantes de las sombras"},
            {name: "Grendrik", meaning: " Destructor de bestias", origin: "Lengua de los cazadores legendarios"},
            {name: "Gaelmir", meaning: "Guerrero del río", origin: " Idioma de los pueblos fluviales"},
        //H *****
            {name: "Haldric", meaning: "Líder de la fortaleza", origin: "Lengua de los defensores ancestrales"},
            {name: "Halron", meaning: "Rey del trueno", origin: "Lengua de los señores de la tormenta"},
            {name: "Harkon", meaning: "Guardián del honor", origin: "Dialecto de los caballeros antiguos"},
            {name: "Hirion ", meaning: "Hijo del fuego", origin: " Idioma de los descendientes de las llamas"},
            {name: "Horadrin", meaning: "Maestro de la alquimia", origin: "Lengua de los sabios de las artes ocultas"},
            {name: "Huldrek", meaning: "Protector de los secretos", origin: "Idioma de los guardianes de las runas"},
            {name: "Hendor", meaning: "Señor de la luz", origin: "Lengua de los iluminadores sagrados"},
            {name: "Haelon", meaning: "Forjador del acero", origin: "Idioma de los herreros del valle"},
            {name: "Herion", meaning: "Viento del amanecer", origin: "Lengua de los viajeros del alba"},
            {name: "Haldren", meaning: "El inmortal", origin: "Dialecto de los habitantes de la eterna ciudad"},
            {name: "", meaning: "", origin: ""},
        //I
            {name: "Ivoran", meaning: "Guardián de los secretos", origin: "Dialecto de los custodios de conocimiento"},
            {name: "Ithranor", meaning: " Rey del hielo", origin: " Lengua de los pueblos del ártico"},
            {name: "Invaron", meaning: "Guardián de la justicia", origin: " Idioma de los jueces sagrados"},
            {name: "Ilrion", meaning: "Luz de las estrellas", origin: "Dialecto de los astrólogos celestiales"},
            {name: "Idrel", meaning: "Protector del tiempo", origin: "Lengua de los guardianes del flujo temporal"},
            {name: "Ivendir", meaning: "Guerrero de las arenas", origin: "Dialecto de los nómadas del desierto"},
            {name: "Ilanthor", meaning: "Espíritu del bosque", origin: "Idioma de los druidas de los árboles antiguos"},
            {name: "Isdrin", meaning: "Hijo del invierno", origin: "Lengua de los viajeros de las tierras heladas"},
            {name: "Iralon", meaning: "Voz del trueno", origin: "Dialecto de los cazadores de tormentas"},
            {name: "Imradon", meaning: "Constructor de mundos", origin: "Lengua de los arquitectos divinos"},
            {name: "Ivendar", meaning: "Señor de la sabiduría", origin: "Idioma de los maestros del conocimiento ancestral"},
        //J
            {name: "Jareth", meaning: "Guerrero de fuego", origin: "Lenguaje de los descendientes de la lava"},
            {name: "Jaronis", meaning: "Héroe del amanecer", origin: "Dialecto de los caballeros de la primera luz"},
            {name: "Jorvin", meaning: "Escudo del pueblo", origin: "Idioma de los protectores de las tierras bajas"},
            {name: "Jelthor", meaning: "Portador de la llama eterna", origin: "Lengua de los sacerdotes del fuego sagrado"},
            {name: "Jardrik", meaning: "Defensor del acero", origin: "Dialecto de los herreros de las tierras altas"},
            {name: "Jaeron", meaning: "Guerrero del crepúsculo", origin: "Idioma de los soldados del ocaso"},
            {name: "Jevrik", meaning: "Señor de los cielos", origin: "Lengua de los navegantes del aire"},
            {name: "Jorath", meaning: " Espíritu del mar", origin: " Dialecto de los guardianes del océano profundo"},
            {name: "Jaldren", meaning: "El eterno cazador", origin: "Lengua de los clanes de la caza"},
            {name: "Jendrik", meaning: "Sabio del hielo", origin: "Idioma de los eruditos de las tierras frías"},
            {name: "Jarvor", meaning: "Portador de la tempestad", origin: "Dialecto de los guerreros del trueno"},
        //K *****
            {name: "Kaelthor", meaning: "Destructor de sombras", origin: "Lengua de los luchadores de luz"},
            {name: "Kaendor", meaning: "Guardián de las tierras", origin: "Lengua de los protectores de las planicies"},
            {name: "Kaldron", meaning: "Señor de las cenizas", origin: "Dialecto de los señores volcánicos"},
            {name: "Korvinor", meaning: "Hijo del cuervo", origin: "Idioma de los mensajeros del destino"},
            {name: "Kharon", meaning: "Guerrero del destino", origin: "Lengua de los héroes proféticos"},
            {name: "Klydor", meaning: "Hijo del relámpago", origin: "Idioma de los guardianes de las tormentas"},
            {name: "Krelthor", meaning: "Maestro de la magia oscura", origin: "Lengua de los nigromantes"},
            {name: "Kalthorn", meaning: "Forjador de reinos", origin: "Dialecto de los arquitectos de imperios"},
            {name: "Karion", meaning: "Guardián del valle", origin: "Idioma de los defensores de las montañas"},
            {name: "Korandir", meaning: " Navegante estelar", origin: "Lengua de los viajeros de las estrellas"},
            {name: "", meaning: "", origin: ""},
        //L
            {name: "Lorian", meaning: "Luz de la esperanza", origin: "Idioma de los iluminadores del amanecer"},
            {name: "Lotharion", meaning: "Señor de las sombras", origin: "Lengua de los habitantes del crepúsculo"},
            {name: "Lerian", meaning: "Hijo de la luna", origin: "Dialecto de los guardianes nocturnos"},
            {name: "Lorvenor", meaning: "Cazador de las estrellas", origin: "Idioma de los rastreadores celestiales"},
            {name: "Lendor", meaning: "Guardián de la llama eterna", origin: "Lengua de los sacerdotes del fuego sagrado"},
            {name: "Lyron", meaning: "Portador de la sabiduría", origin: "Dialecto de los antiguos consejeros"},
            {name: "Larethor", meaning: "Guerrero de la luz", origin: "Idioma de los protectores del amanecer"},
            {name: "Lethor", meaning: "Espíritu de la tormenta", origin: "Lengua de los navegantes del trueno"},
            {name: "Lanrik", meaning: "Señor del acero", origin: "Dialecto de los herreros imperiales"},
            {name: "Lydren", meaning: "Viento del valle", origin: "Idioma de los clanes de las montañas"},
            {name: "Lumion", meaning: "Brillo de esperanza", origin: "Dialecto de los iluminadores del crepúsculo"},
        //M
            {name: "Maldrek", meaning: "Destructor de enemigos", origin: "Dialecto de los guerreros del caos"},
            {name: "Maelor", meaning: "Sabio de las montañas", origin: "Idioma de los eruditos de las cumbres"},
            {name: "Mavrik", meaning: "Guerrero solitario", origin: "Lengua de los nómadas del norte"},
            {name: "Maldrin", meaning: "Señor de los fuegos", origin: "Dialecto de los sacerdotes de la llama"},
            {name: "Mordran", meaning: "Guardián de las sombras", origin: "Lengua de los protectores de la noche"},
            {name: "Myron", meaning: "Hijo de la luna", origin: "Idioma de los viajeros nocturnos"},
            {name: "Marvor", meaning: " Portador de la justicia", origin: "Dialecto de los caballeros sagrados"},
            {name: "Malron", meaning: "Espíritu de los ríos", origin: "Lengua de los guardianes acuáticos"},
            {name: "Morion", meaning: "Cazador de dragones", origin: "Dialecto de los guerreros legendarios"},
            {name: "Malkar", meaning: "Héroe de la oscuridad", origin: "Lengua de los clanes de las tierras olvidadas"},
            {name: "Meldir", meaning: "Guardián de la armonía", origin: "Idioma de los protectores del equilibrio"},
        //N
            {name: "Nerion", meaning: "Hijo del océano", origin: "Lenguaje de los navegantes del mar"},
            {name: "Naldor ", meaning: "Señor de los vientos", origin: "Lengua de los navegantes del aire"},
            {name: "Narvik", meaning: "Guerrero incansable", origin: "Dialecto de los clanes de la tundra"},
            {name: "Neydrin", meaning: "Portador del relámpago", origin: "Idioma de los magos de las tormentas"},
            {name: "Nerion", meaning: " Hijo de las olas", origin: "Dialecto de los habitantes del océano"},
            {name: "Nethor", meaning: "Espíritu de la tierra", origin: "Lengua de los guardianes del suelo fértil"},
            {name: "Nardrik", meaning: "Defensor de las ciudades", origin: " Idioma de los señores de los castillos"},
            {name: "Norvinor", meaning: "Sabio de los valles", origin: "Dialecto de los eruditos de las tierras bajas"},
            {name: "Narlon", meaning: "Señor del acero", origin: " Lengua de los maestros forjadores"},
            {name: "Naelor", meaning: " Guerrero de la aurora", origin: " Idioma de los protectores del amanecer"},
            {name: "Nivor", meaning: "Espada de la justicia", origin: "Dialecto de los paladines del orden"},
        //Ñ
        //O
            {name: "Orinols", meaning: "Estrella fugaz", origin: "Idioma de los astrónomos místicos"},
            {name: "Orlith", meaning: "Guardián del tiempo", origin: "Lengua de los vigilantes eternos"},
            {name: "Odran", meaning: "Señor del trueno", origin: " Idioma de los pueblos de las tormentas"},
            {name: "Orelion", meaning: "Hijo del cielo", origin: "Dialecto de los habitantes de las alturas"},
            {name: "Ondrik", meaning: "Forjador de destinos", origin: "Lengua de los arquitectos del mundo"},
            {name: "Otharion", meaning: "Guerrero inmortal", origin: " Idioma de los héroes legendarios"},
            {name: "Orvik", meaning: "Portador de la luz", origin: "Dialecto de los iluminadores del crepúsculo"},
            {name: "Odrion", meaning: "Espíritu del océano", origin: "Lengua de los habitantes del gran abismo"},
            {name: "Osrandor", meaning: "Protector de la esperanza", origin: "Dialecto de los defensores de la última fortaleza"},
            {name: "Onthor", meaning: "Señor de las sombras", origin: "Idioma de los gobernantes del reino oscuro"},
            {name: "Ovion", meaning: " El eterno", origin: "Dialecto de los sabios de la eternidad"},
        //P
            {name: "Pyron", meaning: "Fuego eterno", origin: "Lengua de los maestros del volcán"},
            {name: "Pyros", meaning: "Hijo del fuego", origin: "Lengua de los druidas de las llamas"},
            {name: "Parion", meaning: "Guardián del crepúsculo", origin: "Dialecto de los vigilantes del ocaso"},
            {name: "Paldrek", meaning: "Defensor del reino", origin: "Idioma de los caballeros reales"},
            {name: "Palthor", meaning: "Espíritu de la tormenta", origin: "Lengua de los magos del trueno"},
            {name: "Pirathor", meaning: "Viento de las llanuras", origin: "Dialecto de los guerreros de las tierras abiertas"},
            {name: "Pendor", meaning: "Forjador de glorias", origin: "Idioma de los constructores de imperios"},
            {name: "Pharlon", meaning: "Hijo de las estrellas", origin: "Lengua de los astrónomos antiguos"},
            {name: "Promar", meaning: "Señor de las profundidades", origin: "Dialecto de los habitantes del océano abisal"},
            {name: "Pherion", meaning: "Luz de las sombras", origin: "Idioma de los sabios oscuros"},
            {name: "Poldren", meaning: "Protector de las tierras", origin: "Dialecto de los guardianes de los campos fértiles"},
        //Q
            {name: "Quorim", meaning: "Guardián de la verdad", origin: "Dialecto de los consejeros sangrados"},
            {name: "Quendrik", meaning: "Héroe de la oscuridad", origin: "Lengua de los vigilantes nocturnos"},
            {name: "Quorneth", meaning: "Guardián del viento", origin: "Dialecto de los guerreros del cielo"},
            {name: "Qaldrin", meaning: "Espíritu de la montaña", origin: "Idioma de los gigantes de las cumbres"},
            {name: "Quorin", meaning: "Señor de las llamas", origin: "Lengua de los magos del fuego eterno"},
            {name: "Quirion", meaning: "Portador de la verdad", origin: "Dialecto de los jueces ancestrales"},
            {name: "Quelthar", meaning: "Defensor del amanecer", origin: "Idioma de los protectores de la primera luz"},
            {name: "Qerion", meaning: "Sabio del hielo", origin: "Lengua de los viajeros de las tierras gélidas"},
            {name: "Quildor", meaning: "Guerrero del trueno", origin: "Dialecto de los luchadores de la tormenta"},
            {name: "Quarnor", meaning: "Hijo del acero", origin: "Lengua de los herreros inmortales"},
            {name: "Quarlon", meaning: "El eterno viajero", origin: "Idioma de los nómadas de las estrellas"},
        //R
            {name: "Ragnar", meaning: "Guerrero del trueno", origin: "Lengua de los vikingos míticos"},
            {name: "Raldir", meaning: "Defensor de los reinos", origin: "Lengua de los guerreros reales"},
            {name: "Ravion", meaning: "Señor del rayo", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        //S
            {name: "Sylas", meaning: "Protector de los bosques", origin: "Idioma de los druida ancestrales"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        //T
            {name: "Thalon", meaning: "Noble y fuerte", origin: "Lenguaje de los señores del reino"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        //U
            {name: "Ulyric", meaning: "Legado de sabiduría", origin: "Dialecto de los eruditos de la Antigua Orden"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        //V
            {name: "Varek", meaning: "Destructor de la oscuridad", origin: "Lengua de los Campeones de la Luz"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        //W
            {name: "Wraithor", meaning: "Espíritu guardián", origin: "Idioma de los seres etéreos"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        //X
            {name: "Xandar", meaning: "Defensor de la paz", origin: "Lenuaje de los pacificadores de la era dorada"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        //Y
            {name: "Yorin", meaning: "Amigo leal", origin: "Dialecto de los clanes de los bosques"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        //Z
            {name: "Zarek", meaning: "Sombra del dragón", origin: "Lengua de los descendientes de los dragones"},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
            {name: "", meaning: "", origin: ""},
        {name: "", meaning: "", origin: ""},
/*Me puedes generar una lista de nombres masculinos con todas las letras del abecedario, que tengan significado, un origen y que estos nombres sean de fantasia?*/
        // Agrega más nombres aquí
    ],
    female: [
        { name: "Aeliana", meaning: "Del Sol", origin: "Latino" },
        { name: "Briala", meaning: "Puede ser una variante de Briana", origin: "Desconocido" },
        { name: "Calia", meaning: "Bella", origin: "Griego" },
        { name: "Eldira", meaning: "Usado en literatura de fantasía", origin: "Ficticio" },
        { name: "Fiona", meaning: "Blanca", origin: "Gaélico" },
        { name: "Beatrix", meaning: "Viajera", origin: "Latino" },
        { name: "Callista", meaning: "La más hermosa", origin: "Griego" },
        // Agrega más nombres aquí
    ],
    nonBinary: [
        { name: "Arin", meaning: "Luz", origin: "Hebreo" },
        { name: "Bryn", meaning: "Colina", origin: "Galés" },
        { name: "Dru", meaning: "Sabio", origin: "Celta" },
        { name: "Ezra", meaning: "Ayuda", origin: "Hebreo" },
        { name: "Kai", meaning: "Mar", origin: "Hawaiano" },
        { name: "Briar", meaning: "Zarza", origin: "Inglés" },
        { name: "Ciel", meaning: "Cielo", origin: "Francés" },
        // Agrega más nombres aquí
    ]
};


function generateName() {
    const gender = document.getElementById('gender').value;
    const initial = document.getElementById('initial').value;
    const nameList = names[gender];

    if (!nameList || nameList.length === 0) {
        alert("No hay nombres disponibles para este género.");
        return;
    }

    // Filtrar los nombres por la inicial seleccionada
    const filteredNames = initial ? nameList.filter(name => name.name.startsWith(initial)) : nameList;
    
    // Verificar si la lista filtrada está vacía
    if (filteredNames.length === 0) {
        alert(`No hay nombres disponibles que empiecen con la letra "${initial}".`);
        return;  // Detener la ejecución si no hay nombres disponibles
    }

    const randomIndex = Math.floor(Math.random() * filteredNames.length);
    const randomName = filteredNames[randomIndex];
    
// Crear el mensaje con el nombre, significado y origen usando etiquetas HTML con clases
    const message = 
                    `<span class="name-title">Nombre:</span> <span class="name">${randomName.name}<br>` +
                    `<span class="meaning-title">Significado:</span> <span class="meaning">${randomName.meaning}<br>` +
                    `<span class="origin-title">Origen:</span> <span class="origin">${randomName.origin}</span>`;
    
    // Mostrar el mensaje en una ventana emergente
    //alert(message);
    
    // También puedes mostrar el nombre en el área designada si lo prefieres
    document.getElementById('name-output').innerHTML = message;
    // Usamos .innerHTML en lugar de .textContent para insertar HTML (como <br>) en el contenido del elemento.
}
// Puedo agregarle también la raza del personaje, origen, inicial, etc.
